Update create_project.yml

diff --git a/.github/workflows/create_project.yml b/.github/workflows/create_project.yml
--- a/.github/workflows/create_project.yml
+++ b/.github/workflows/create_project.yml
@@ -24,17 +24,22 @@ jobs:
             exit 1
           fi
           ONLY_PAINT_FILES=$(python -c "import json; with open('file_metadata.json') as f: files = json.load(f); print('true' if all(f['path'].lower().endswith(('.png', '.pdn')) for f in files if f['path'].lower() != 'preview.png') else 'false')")
-          if [ "$ONLY_PAINT_FILES" = "true" ]; then
-            python create_project_json.py "${PROJECT_NAME}" "$FILE_METADATA" || { echo "Failed to create JSON"; exit 1; }
-            zip -r "${PROJECT_NAME}/Инферно.zip" "${PROJECT_NAME}" -x "${PROJECT_NAME}/preview.png" || { echo "Failed to create ZIP"; exit 1; }
+          python create_project_json.py "${PROJECT_NAME}" "$FILE_METADATA" || { echo "Failed to create JSON"; exit 1; }
+          if [ "$IS_SINGLE_ZIP" = "true" ]; then
+            zip -r "${PROJECT_NAME}/Archive.zip" "${PROJECT_NAME}" || { echo "Failed to create ZIP"; exit 1; }
+          elif [ "$ONLY_PAINT_FILES" = "true" ]; then
+            zip -r "${PROJECT_NAME}/Archive.zip" "${PROJECT_NAME}" -x "${PROJECT_NAME}/preview.png" || { echo "Failed to create ZIP"; exit 1; }
           else
             mkdir -p "${PROJECT_NAME}/Итог" "${PROJECT_NAME}/other"
-            python create_project_json.py "${PROJECT_NAME}" "$FILE_METADATA" || { echo "Failed to create JSON"; exit 1; }
-            zip -r "${PROJECT_NAME}/Инферно.zip" "${PROJECT_NAME}/Итог" "${PROJECT_NAME}/other" || { echo "Failed to create ZIP"; exit 1; }
+            mv "${PROJECT_NAME}"/*.png "${PROJECT_NAME}/Итог" 2>/dev/null || true
+            mv "${PROJECT_NAME}"/*.pdn "${PROJECT_NAME}/Итог" 2>/dev/null || true
+            mv "${PROJECT_NAME}"/* "${PROJECT_NAME}/other" 2>/dev/null || true
+            zip -r "${PROJECT_NAME}/Archive.zip" "${PROJECT_NAME}/Итог" "${PROJECT_NAME}/other" || { echo "Failed to create ZIP"; exit 1; }
           fi
         env:
           PROJECT_NAME: ${{ github.event.client_payload.project_name }}
           FILE_METADATA: ${{ github.event.client_payload.file_metadata }}
+          IS_SINGLE_ZIP: ${{ github.event.client_payload.is_single_zip }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Commit changes
